#!/usr/bin/env bash
# Doubling the number of web servers and making them noth identical
SERVER_NAME=$(hostname)
apt-get update
apt-get install -y nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
CONFIG_FILE="/etc/nginx/sites-available/default"
sed -i "/server_name _;/a \\ \n\tlocation \/redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}" "$CONFIG_FILE"
sed -i "/server_name _;/a \\ \n\terror_page 404 /custom_404.html;" "$CONFIG_FILE"
sed -i "/server_name _;/a \\\n\tadd_header X-Served-By $SERVER_NAME;" /etc/nginx/sites-available/default
sudo service nginx restart
