#!/usr/bin/env bash
# Installing and configuring load balancer
apt-get update
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.0
apt-get install -y haproxy=2.0.\*

CONFIG_FILE="/etc/haproxy/haproxy.cfg"

echo "ENABLED=1" >> /etc/default/haproxy

printf %s "
frontend haproxynode
    bind *:80
    mode http
    default_backend backendnodes

backend backendnodes
    balance roundrobin
    server 824-web-01 34.73.37.244:80 check
    server 824-web-02 34.74.25.167:80 check
" >> "$CONFIG_FILE"

sudo service haproxy start
