#!/usr/bin/env bash
# Installing and configuring load balancer
sudo apt-get update
# apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.0
sudo apt-get install -y haproxy=2.0.\*

CONFIG_FILE="/etc/haproxy/haproxy.cfg"

echo "ENABLED=1" >> /etc/default/haproxy

printf %s "
frontend haproxynode
\tbind *:80
\tmode http
\tdefault_backend backendnodes

backend backendnodes
\tbalance roundrobin
\tserver 5722-web-01 3.80.137.253:80 check
\tserver 5722-web-02 54.204.94.209:80 check
" >> "$CONFIG_FILE"

sudo service haproxy start
