#!/usr/bin/env bash
# Installing Nginx and configuring it
apt-get update
apt-get install -y nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
cp 5-design_a_beautiful_404_page.html /var/www/html/custom_404.html
CONFIG_FILE="/etc/nginx/sites-available/default"
sed -i "/server_name _;/a \\ \n\tlocation \/redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}" "$CONFIG_FILE"
sed -i "/server_name _;/a \\ \n\terror_page 404 /custom_404.html;" "$CONFIG_FILE"

sudo service nginx restart
