#!/usr/bin/env bash
# Script that transfers a file from a client to server
if [ $# -lt 5 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ $# -gt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -B -i "$4"  "$1" "$3"@"$2":/~ /
fi
