#!/usr/bin/env bash
# Installing Nginx and configuring it
apt-get update
apt-get install -y nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
CONFIG_FILE="/etc/nginx/sites-available/default"
sed -i "/server_name _;/a \\ \n\tlocation \/redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}" "$CONFIG_FILE"
sudo service nginx restart
