#!/usr/bin/env bash
# Installing Nginx and configuring it
apt-get update
apt-get install -y nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
CONFIG_FILE="/etc/nginx/sites-available/default"
sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" "$CONFIG_FILE"
sudo service nginx restart
